### ISSUE TITLE
Provide opt-in email for notification on failed build

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/kernels#4]
> As a maintainer, when my kernel fails some tests, I would like to get an email!

In `kernel/xyzkernel/meta.whatever`, offer a place to capture notifications, starting with email:
```yaml
"notifications": {
  "email": ["maintainer@example.com", "mailing-list@project.org"],
  "github": "user/project"
}
```

Investigate proper way to do sending/remailing for notifications.
